query EventStandings($eventId: ID!, $page: Int!, $perPage: Int!) {
  event(id: $eventId) {
    id
    name
    numEntrants
    standings(query: {
      perPage: $perPage,
      page: $page
    }){
      nodes {
        placement
        entrant {
          id
          name
          participants{
            id
            user{
              name
              authorizations(types: TWITTER){
                externalUsername
              }
            }
          }
        }
      }
    }
  }
}